;; Triangle, pentagonal, and hexagonal numbers are generated by the
;; following formulae:

;; Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
;; Pentagonal  Pn=n(3n−1)/2  1, 5, 12, 22, 35, ...
;; Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...

;; It can be verified that T285 = P165 = H143 = 40755.

;; Find the next triangle number that is also pentagonal and hexagonal.

(defun penta-p (n)
  (let ((i (truncate (1+ (isqrt (1+ (* 24 n)))) 6)))
    (= n (/ (* i (1- (* 3 i))) 2))))

(defun hexa (n)
  (* n (1- (* 2 n))))

(loop for i from 144 when (penta-p (hexa i)) return (hexa i)) ; => 1533776805
