;; The sequence of triangle numbers is generated by adding the natural
;; numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
;; 28. The first ten terms would be:

;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

;; Let us list the factors of the first seven triangle numbers:

;;      1: 1
;;      3: 1,3
;;      6: 1,2,3,6
;;     10: 1,2,5,10
;;     15: 1,3,5,15
;;     21: 1,3,7,21
;;     28: 1,2,4,7,14,28

;; We can see that 28 is the first triangle number to have over five
;; divisors.

;; What is the value of the first triangle number to have over five hundred
;; divisors?

(defun divisors (n)
  (let ((divs 1))
    (loop for i from 2 until (> i n) do
      (let ((times 1))
        (loop while (= 0 (mod n i)) do
          (setf n (/ n i))
          (incf times))
        (setf divs (* divs times))))
    divs))

(loop for i from 2 and tn = 1 then (+ tn i)
      until (< 500 (divisors tn))
      finally (return tn))

;; => 76576500
